# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poputchik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('longt', models.FloatField()),
                ('loc', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poputka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('longt', models.FloatField()),
                ('loc', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
