# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poputchik',
            name='loc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poputka',
            name='loc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
