# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-24 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial2'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0432\u0440\u0435\u043c\u044f'),
        ),
    ]
