# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160915_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poputchik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('point_a', models.CharField(max_length=50)),
                ('point_b', models.CharField(max_length=50)),
                ('photo_url', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=750)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poputka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_car', models.CharField(choices=[('\u043b\u0435\u0433\u043a\u043e\u0432\u0430\u044f', '\u043b\u0435\u0433\u043a\u043e\u0432\u0430\u044f'), ('\u0433\u0440\u0443\u0437\u043e\u0432\u0430\u044f', '\u0433\u0440\u0443\u0437\u043e\u0432\u0430\u044f')], max_length=20)),
                ('car_number', models.CharField(max_length=10, null=True)),
                ('car_model', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=50)),
                ('point_a', models.CharField(max_length=50)),
                ('point_b', models.CharField(max_length=50)),
                ('photo_url', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=750)),
                ('price', models.CharField(max_length=10)),
                ('type_of_motion', models.CharField(choices=[('\u043f\u043e \u0441\u0442\u0440\u0430\u043d\u0435', '\u043f\u043e \u0441\u0442\u0440\u0430\u043d\u0435'), ('\u043f\u043e \u0433\u043e\u0440\u043e\u0434\u0443', '\u043f\u043e \u0433\u043e\u0440\u043e\u0434\u0443'), ('\u043f\u043e \u043c\u0438\u0440\u0443', '\u043f\u043e \u043c\u0438\u0440\u0443')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('extra_phone', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=2)),
                ('sex', models.CharField(choices=[('\u041c\u0443\u0436', '\u041c\u0443\u0436'), ('\u0416\u0435\u043d', '\u0416\u0435\u043d')], max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='poputka',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.UserNew', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='poputchik',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.UserNew', verbose_name='user'),
        ),
    ]
