# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_schedule_ison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ison',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ison',
            field=models.CharField(max_length=100, null=True, verbose_name='ison'),
        ),
    ]
