# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160915_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserNew',
            new_name='User',
        ),
    ]
