# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170529_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='\u0438\u043c\u044f')),
                ('surname', models.CharField(max_length=20, null=True, verbose_name='\u0444\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='\u043f\u0430\u0440\u043e\u043b\u044c')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='\u0442.\u043d\u043e\u043c\u0435\u0440')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
        ),
    ]
